package zsy.CloudMe.mybatis.model;

import java.math.BigDecimal;

public class Account {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column account.uuid
	 *
	 * @mbg.generated Mon Jul 31 09:43:45 CST 2017
	 */
	private String uuid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column account.username
	 *
	 * @mbg.generated Mon Jul 31 09:43:45 CST 2017
	 */
	private String username;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column account.password
	 *
	 * @mbg.generated Mon Jul 31 09:43:45 CST 2017
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column account.uuid
	 *
	 * @return the value of account.uuid
	 *
	 * @mbg.generated Mon Jul 31 09:43:45 CST 2017
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column account.uuid
	 *
	 * @param uuid
	 *            the value for account.uuid
	 *
	 * @mbg.generated Mon Jul 31 09:43:45 CST 2017
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column account.username
	 *
	 * @return the value of account.username
	 *
	 * @mbg.generated Mon Jul 31 09:43:45 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column account.username
	 *
	 * @param username
	 *            the value for account.username
	 *
	 * @mbg.generated Mon Jul 31 09:43:45 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column account.password
	 *
	 * @return the value of account.password
	 *
	 * @mbg.generated Mon Jul 31 09:43:45 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column account.password
	 *
	 * @param password
	 *            the value for account.password
	 *
	 * @mbg.generated Mon Jul 31 09:43:45 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	public Account(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Account(String uuid,String username, String password) {
		this.uuid=uuid;
		this.username = username;
		this.password = password;
	}
	public boolean checkUsernamePassword(Account user) {
		if (user.getUsername() == this.username && user.getPassword() == this.password)
			return true;
		else
			return false;
	}
}